# -*- coding: utf-8 -*-
"""24F-0016_BSAI-4A-AI-ASS#02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13EWvV5zy0rW31ZdPO1q1pUqH8l9dN3YL
"""

import tkinter as tk
from tkinter import ttk
import heapq
import random
import time
import math

CELL_SIZE = 25


class PathfindingApp:

    def __init__(self, root):
        self.root = root
        self.root.title("Dynamic Pathfinding Agent")

        self.rows = 20
        self.cols = 20

        self.algorithm = tk.StringVar(value="A*")
        self.heuristic_type = tk.StringVar(value="Manhattan")
        self.dynamic_mode = tk.BooleanVar(value=False)

        self.create_controls()
        self.create_grid()

        self.start = (0, 0)
        self.goal = (self.rows - 1, self.cols - 1)

        self.agent_position = self.start
        self.current_path = []

        self.nodes_visited = 0
        self.execution_time = 0
        self.path_cost = 0

        self.draw_grid()


    def create_controls(self):
        frame = tk.Frame(self.root)
        frame.pack()

        ttk.Label(frame, text="Algorithm:").grid(row=0, column=0)
        ttk.OptionMenu(frame, self.algorithm, "A*", "A*", "GBFS").grid(row=0, column=1)

        ttk.Label(frame, text="Heuristic:").grid(row=0, column=2)
        ttk.OptionMenu(frame, self.heuristic_type, "Manhattan", "Manhattan", "Euclidean").grid(row=0, column=3)

        ttk.Checkbutton(frame, text="Dynamic Mode", variable=self.dynamic_mode).grid(row=0, column=4)

        ttk.Button(frame, text="Generate Random Map", command=self.generate_random_map).grid(row=0, column=5)
        ttk.Button(frame, text="Start Search", command=self.start_search).grid(row=0, column=6)

        self.metrics_label = ttk.Label(frame, text="Nodes: 0  Cost: 0  Time: 0 ms")
        self.metrics_label.grid(row=1, column=0, columnspan=7)


    def create_grid(self):
        self.canvas = tk.Canvas(self.root,
                                width=self.cols * CELL_SIZE,
                                height=self.rows * CELL_SIZE)
        self.canvas.pack()

        self.grid = [[0 for _ in range(self.cols)] for _ in range(self.rows)]
        self.canvas.bind("<Button-1>", self.toggle_wall)

    def draw_grid(self):
        self.canvas.delete("all")
        for r in range(self.rows):
            for c in range(self.cols):
                x1 = c * CELL_SIZE
                y1 = r * CELL_SIZE
                x2 = x1 + CELL_SIZE
                y2 = y1 + CELL_SIZE

                color = "white"

                if (r, c) == self.start:
                    color = "blue"
                elif (r, c) == self.goal:
                    color = "purple"
                elif self.grid[r][c] == 1:
                    color = "black"
                elif (r, c) in self.current_path:
                    color = "green"

                self.canvas.create_rectangle(x1, y1, x2, y2, fill=color, outline="gray")

    def toggle_wall(self, event):
        c = event.x // CELL_SIZE
        r = event.y // CELL_SIZE

        if (r, c) != self.start and (r, c) != self.goal:
            self.grid[r][c] = 1 - self.grid[r][c]
            self.draw_grid()

    def generate_random_map(self):
        density = 0.3
        for r in range(self.rows):
            for c in range(self.cols):
                if (r, c) != self.start and (r, c) != self.goal:
                    self.grid[r][c] = 1 if random.random() < density else 0
        self.draw_grid()


    def heuristic(self, a, b):
        if self.heuristic_type.get() == "Manhattan":
            return abs(a[0] - b[0]) + abs(a[1] - b[1])
        else:
            return math.sqrt((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2)


    def get_neighbors(self, node):
        r, c = node
        neighbors = []
        directions = [(1,0), (-1,0), (0,1), (0,-1)]

        for dr, dc in directions:
            nr, nc = r + dr, c + dc
            if 0 <= nr < self.rows and 0 <= nc < self.cols:
                if self.grid[nr][nc] == 0:
                    neighbors.append((nr, nc))
        return neighbors

    def search(self, start):
        open_list = []
        heapq.heappush(open_list, (0, start))

        came_from = {}
        g_score = {start: 0}

        self.nodes_visited = 0

        while open_list:
            _, current = heapq.heappop(open_list)
            self.nodes_visited += 1

            if current == self.goal:
                return self.reconstruct_path(came_from, current)

            for neighbor in self.get_neighbors(current):
                tentative_g = g_score[current] + 1

                if neighbor not in g_score or tentative_g < g_score[neighbor]:
                    came_from[neighbor] = current
                    g_score[neighbor] = tentative_g

                    if self.algorithm.get() == "A*":
                        f = tentative_g + self.heuristic(neighbor, self.goal)
                    else:
                        f = self.heuristic(neighbor, self.goal)

                    heapq.heappush(open_list, (f, neighbor))

        return []

    def reconstruct_path(self, came_from, current):
        path = []
        while current in came_from:
            path.append(current)
            current = came_from[current]
        path.reverse()
        return path


    def spawn_dynamic_obstacle(self):
        if random.random() < 0.05:
            r = random.randint(0, self.rows - 1)
            c = random.randint(0, self.cols - 1)

            if (r, c) not in [self.start, self.goal, self.agent_position]:
                self.grid[r][c] = 1

                if (r, c) in self.current_path:
                    return True
        return False


    def start_search(self):
        start_time = time.time()

        self.agent_position = self.start
        self.current_path = self.search(self.agent_position)

        if not self.current_path:
            print("No Path Found")
            return

        self.path_cost = len(self.current_path)

        end_time = time.time()
        self.execution_time = (end_time - start_time) * 1000

        self.update_metrics()
        self.animate_movement()

    def animate_movement(self):
        if not self.current_path:
            return

        next_step = self.current_path.pop(0)
        self.agent_position = next_step

        if self.dynamic_mode.get():
            blocked = self.spawn_dynamic_obstacle()
            if blocked:
                self.current_path = self.search(self.agent_position)

        self.draw_grid()
        self.root.after(200, self.animate_movement)

    def update_metrics(self):
        self.metrics_label.config(
            text=f"Nodes: {self.nodes_visited}   Cost: {self.path_cost}   Time: {round(self.execution_time,2)} ms"
        )



if __name__ == "__main__":
    root = tk.Tk()
    app = PathfindingApp(root)
    root.mainloop()